"use client";

import {
	Box,
	Paper,
	Typography,
	TextField,
	MenuItem,
	Stack,
	Slider,
	Alert,
	Chip,
} from "@mui/material";
import { useMemo, useState } from "react";
import CodeBlock from "./CodeBlock";

/**
 * Interactive HTCondor submit file builder. Users tweak inputs and see the
 * resulting .sub file update live, with validation tips.
 */
export default function SubmitFileBuilder() {
	const [executable, setExecutable] = useState("hello-ospool.sh");
	const [queueN, setQueueN] = useState(3);
	const [duration, setDuration] = useState<"Medium" | "Long">("Medium");
	const [cpus, setCpus] = useState(1);
	const [memoryGB, setMemoryGB] = useState(1);
	const [diskGB, setDiskGB] = useState(5);
	const [os, setOs] = useState("RHEL 9");

	const submitFile = useMemo(
		() => `# ${executable.replace(/\.sh$/, "")}.sub
# Generated by the interactive course builder

executable = ${executable}
arguments  = $(Process)

log    = ${executable.replace(/\.sh$/, "")}_$(Cluster)_$(Process).log
error  = ${executable.replace(/\.sh$/, "")}_$(Cluster)_$(Process).err
output = ${executable.replace(/\.sh$/, "")}_$(Cluster)_$(Process).out

+JobDurationCategory = "${duration}"

requirements   = (OSGVO_OS_STRING == "${os}")
request_cpus   = ${cpus}
request_memory = ${memoryGB}GB
request_disk   = ${diskGB}GB

queue ${queueN}
`,
		[executable, queueN, duration, cpus, memoryGB, diskGB, os],
	);

	const warnings: string[] = [];
	if (cpus > 1) warnings.push("Requesting >1 CPU only helps if your software is actually multi-threaded. Most software uses 1 CPU.");
	if (memoryGB > 16) warnings.push("Large memory requests reduce the number of slots that can run your job. Test smaller first.");
	if (diskGB > 50) warnings.push("Consider whether inputs/outputs that large belong in /protected rather than /home.");
	if (duration === "Long" && queueN > 1000) warnings.push("Long jobs at large scale: contact a facilitator or implement self-checkpointing.");

	return (
		<Paper variant="outlined" sx={{ p: { xs: 2, sm: 3 }, my: 3, borderRadius: 2 }}>
			<Typography variant="h6" sx={{ fontWeight: 700, mb: 0.5 }}>
				🛠️ Try it: build your own submit file
			</Typography>
			<Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
				Adjust the controls — the <code>.sub</code> file on the right updates live.
			</Typography>

			<Box
				sx={{
					display: "grid",
					gridTemplateColumns: { xs: "1fr", md: "1fr 1.2fr" },
					gap: 3,
				}}
			>
				<Stack spacing={2.5}>
					<TextField
						label="Executable filename"
						value={executable}
						onChange={(e) => setExecutable(e.target.value || "hello-ospool.sh")}
						size="small"
						fullWidth
					/>
					<TextField
						label="Requested OS"
						value={os}
						onChange={(e) => setOs(e.target.value)}
						select
						size="small"
						fullWidth
					>
						<MenuItem value="RHEL 9">RHEL 9</MenuItem>
						<MenuItem value="RHEL 8">RHEL 8</MenuItem>
					</TextField>
					<TextField
						label="Job Duration Category"
						value={duration}
						onChange={(e) => setDuration(e.target.value as "Medium" | "Long")}
						select
						size="small"
						fullWidth
						helperText={
							duration === "Medium"
								? "Expected <10 hrs · max 20 hrs"
								: "Expected <20 hrs · max 40 hrs"
						}
					>
						<MenuItem value="Medium">Medium (default, &lt;10 hrs)</MenuItem>
						<MenuItem value="Long">Long (&lt;20 hrs)</MenuItem>
					</TextField>

					<Box>
						<Typography variant="body2" sx={{ fontWeight: 600 }}>
							request_cpus: <Chip label={cpus} size="small" />
						</Typography>
						<Slider value={cpus} min={1} max={8} step={1} marks onChange={(_, v) => setCpus(v as number)} />
					</Box>

					<Box>
						<Typography variant="body2" sx={{ fontWeight: 600 }}>
							request_memory: <Chip label={`${memoryGB} GB`} size="small" />
						</Typography>
						<Slider value={memoryGB} min={1} max={32} step={1} onChange={(_, v) => setMemoryGB(v as number)} />
					</Box>

					<Box>
						<Typography variant="body2" sx={{ fontWeight: 600 }}>
							request_disk: <Chip label={`${diskGB} GB`} size="small" />
						</Typography>
						<Slider value={diskGB} min={1} max={100} step={1} onChange={(_, v) => setDiskGB(v as number)} />
					</Box>

					<Box>
						<Typography variant="body2" sx={{ fontWeight: 600 }}>
							queue (number of jobs): <Chip label={queueN} size="small" />
						</Typography>
						<Slider
							value={queueN}
							min={1}
							max={10000}
							step={1}
							onChange={(_, v) => setQueueN(v as number)}
							scale={(x) => x}
						/>
					</Box>
				</Stack>

				<Box>
					<CodeBlock code={submitFile} filename={`${executable.replace(/\.sh$/, "")}.sub`} />
					{warnings.length > 0 && (
						<Stack spacing={1} sx={{ mt: 1 }}>
							{warnings.map((w, i) => (
								<Alert key={i} severity="warning" sx={{ py: 0 }}>
									{w}
								</Alert>
							))}
						</Stack>
					)}
				</Box>
			</Box>
		</Paper>
	);
}

